# Generated by Django 5.1.2 on 2024-10-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('no', 'Prefiero no responder')], max_length=30)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
